swagger: "2.0"  # The version of the Swagger API
info:
    # A user defined description of what the API provides or is about
    description: This is the swagger file that goes with our server code
    # User defined version value for the API
    version: "1.0.0"
    # User defined title included in the Connexion generated UI system
    title: Swagger REST Article
consumes:  # Tells Connexion what MIME type is expected by the API
    - application/json
produces:  # Tells Connexion what content type is expected by the caller of the API
    - application/json

# Defines the root of the API (like a namespace the REST API will come from)
basePath: /api

# Paths supported by the server application
paths:
    # The '/people' URL endpoint
    /people:
        # Definitions associated with HTTP GET
        get:
            # Defines the Python import path/function that will respond to HTTP GET
            operationId: people.read_all
            # Defines a grouping for the UI interface (all CRUD methods defined for /people will share this tag definition
            tags:
                - people
            # Defines the UI interface display text
            summary: Read the entire set of people, sorted by last name
            # Defines what the UI interface will display for implmentation notes
            description: Read the entire set of people, sorted by last name
            responses:
                200:
                    description: Successfully read people set operation
                    schema:
                        type: array
                        items:
                            properties:
                                person_id:
                                    type: integer
                                    description: Id of the person
                                fname:
                                    type: string
                                    description: First name of the person
                                lname:
                                    type: string
                                    description: Last name of the person
                                timestamp:
                                    type: string
                                    description: Create/Update timestamp of the person
                                notes:
                                    type: array
                                    items:
                                        properties:
                                            person_id:
                                                type: integer
                                                description: Id of person this note is associated with
                                            note_id:
                                                type: integer
                                                description: Id of this note
                                            content:
                                                type: string
                                                description: content of this note
                                            timestamp:
                                                type: string
                                                description: Create/Update timestamp of this note
        post:
            operationId: people.create
            tags:
                - people
            summary: Create a person
            description: Create a new person
            parameters:
                - name: person
                  in: body
                  description: Person to create
                  required: True
                  schema:
                    type: object
                    properties:
                        fname:
                            type: string
                            description: First name of person to create
                        lname:
                            type: string
                            description: Last name of person to create
            responses:
                201:
                    description: Successfully created person
                    schema:
                        properties:
                            person_id:
                                type: integer
                                description: Id of the person
                            fname:
                                type: string
                                description: First name of the person
                            lname:
                                type: string
                                description: Last name of the person
                            timestamp:
                                type: string
                                description: Creation/Update timestamp of the person record

    /people/{person_id}:
        get:
            operationId: people.read_one
            tags:
                - people
            summary: Read one person
            description: Read one person
            parameters:
                - name: person_id
                  in: path
                  description: Id of the person to get
                  type: integer
                  required: True
            responses:
                200:
                    description: Successfully read person from people data operation
                    schema:
                        type: object
                        properties:
                            person_id:
                                type: string
                                description: Id of the person
                            fname:
                                type: string
                                description: First name of the person
                            lname:
                                type: string
                                description: Last name of the person
                            timestamp:
                                type: string
                                description: Creation/Update timestamp of the person record
        put:
            operationId: people.update
            tags:
                - people
            summary: Update a person
            description: Update a person
            parameters:
                - name: person_id
                  in: path
                  description: Id of the person to update
                  type: integer
                  required: True
                - name: person
                  in: body
                  schema:
                    type: object
                    properties:
                        fname:
                            type: string
                            description: First name of the person
                        lname:
                            type: string
                            description: Last name of the person
            responses:
                200:
                    description: Successfully updated person
                    schema:
                        properties:
                            person_id:
                                type: string
                                description: Id of the person in the database
                            fname:
                                type: string
                                description: First name of the person
                            lname:
                                type: string
                                description: Last name of the person
                            timestamp:
                                type: string
                                description: Creation/Update timestamp of the person record
        delete:
            operationId: people.delete
            tags:
                - people
            summary: Delete a person from the people list
            description: Delete a person
            parameters:
                - name: person_id
                  in: path
                  type: integer
                  description: Id of the person to delete
                  required: True
            responses:
                200:
                    description: Successfully deleted a person
